#!/bin/bash

# packages
export DEBIAN_FRONTEND=noninteractive
if [ -z "$1" ]; then
~/bin/fix-apt-sources
sudo apt-get update
sudo apt-get full-upgrade -y -q
if [ $? != 0 ]; then
    sudo apt --fix-broken install
    sudo apt-get full-upgrade -y -q
fi
sudo apt-get autoclean
sudo apt-get clean
sudo apt-get autoremove -y
fi

