#!/bin/bash

dir=$(dirname "$(readlink -f "$0")")
usage="usage: curcon ...
1 [inf_file::required] \"Install.inf\" \"installer.inf\" ...
2 [nconvert_path::optional] \"nconvert\" \"/opt/bin/nconvert\" ...
3 [rate_num::optional] \"42\" \"100\" \"150\" ...
4 [hotspots_num::optional] \"x y\" \"10 4\"\"0 0\" ...
5 [size_num::required] \"24\" \"32\" \"48\" \"64\" ...
6 [action_name::required] \"gen\" \"pack\" \"gcpack\"
7 [theme_name::optional] \"MyCursorTheme\" ...
- order must be respected
- skip optional parameters by typing \"\"
example: 
curcon \"(Installer).inf\" \"\" \"\" \"\" \"32\" \"genpack\" \"CursorTheme\""
name="$7"
action="$6"
size="$5"
hotspots="$4"
installer="$1"
convert="$2"
rate="$3"
strings="`cat \"$installer\" 2>/dev/null | grep \"Strings\" -A 1000 | grep \"\.ani\" -A 1000`"

if [[ -z "$action" || -z "$strings" || -z "$size" ]] ; then
	echo "$usage"
	exit 1
fi

if [[ -z "$convert" ]] ; then
	convert="nconvert"
fi

if [[ -z "$rate" ]] ; then
	rate=100
fi

if [[ -z "$hotspots" ]] ; then
	hotspots="0 0"
fi

if [[ -z "$name" ]] ; then
	name="`pwd`"
fi

if [[ "$action" == "gen" || "$action" == "gcpack" ]] ; then 

	rm -rf out
	mkdir -p out
	
	IFS=$'\n'
	for ani in $strings ; do
		target="`echo "$ani" | awk '{print $1}'`"
		filename=`echo "$ani" | sed 's~.*=\s*\"\(.*\)\"~\1~'`
	        filename=`printf %b $filename | sed 's~^\$~~' | sed 's~\\r~~' | sed 's~'\''~~'`
		cp -rp "`echo $filename`" out/tmp.ani
		$convert -xall -out png -o out/${target}.png out/tmp.ani
	done
	
	rm -f out/tmp.ani

fi

if [[ "$action" == "pack" || "$action" == "gcpack" ]] ; then
	cp -rp ${dir}/template out/${name}
	rm -f out/curconfig_*
	for role in `find out/ -maxdepth 1 -type f | xargs -I {} basename {} | sed 's~\.png\|-.*~~' | sort -u`; do
		rm -f out/${name}/${role}
		frames=`find out/ -type f | grep "$role" | xargs -I {} basename {}`
		fc=`echo "$frames" | wc -l`
		c=0
		if [[ "$fc" -gt 1 ]] ; then
			for frame in $frames ; do
				if [[ "$c" == "$fc" ]] ; then
					rate_l="999999"
				else
					rate_l="$rate"
				fi
				echo "$size $hotspots $frame $rate_l" >> out/curconfig_${role}
				c=$((c+1))
			done
		else
			echo "$size $hotspots $frames" > out/curconfig_${role}
		fi
		rm -f out/${name}/cursors/${role}
		xcursorgen -p out out/curconfig_${role} out/${name}/cursors/${role}
	done
	sed -i 's~Name=.*~Name='${name}'~' out/${name}/index.theme
	cat out/${name}/index.theme
fi

if [[ "$action" == "xgen" ]] ; then
	rm -rf out/${name}
	cp -rp ${dir}/template out/${name}
	for conf in `find out/ -maxdepth 1 -name "curconfig_*"` ; do
		role=`echo $conf | sed 's~.*_~~'`
		rm -f out/${name}/cursors/${role}
		xcursorgen -p out $conf out/${name}/cursors/${role}
	done
	sed -i 's~Name=.*~Name='${name}'~' out/${name}/index.theme
	cat out/${name}/index.theme
fi