#!/bin/zsh



mydom=win10
DOM=$1
prefix=/home/fra
genxml=${prefix}/.bin/virshxmlgen
vgatolinux=${prefix}/kvm/vgatolinux.sh
vgatovfio=${prefix}/kvm/vgatovfio.sh
kb=${prefix}/kvm/topre.xml
mouse=${prefix}/kvm/roccat.xml
logs=${prefix}/.tmp/log

rgx='prepare|start|started|stopped|release'
if [ "$DOM" = "$mydom" ]; then
    echo "$@" >> $logs
    case "$2" in
        "start")
            ;;
        "prepare")
            echo "$@" > $logs
            ## kill kodi bacause it leaves listening ports hanging
            kill -9 $(pgrep kodi); kill -9 $(pgrep quasar)
            ## stop X if using only 1 gpu
            systemctl stop nodm

            ## vfio
            modprobe -a vfio vfio-pci
            sleep 1
            zsh ${vgatovfio} &>>$logs

            ## cpu tuning governor
            modprobe msr ## cpufreq monitor driver
            modprobe -a virtio virtio-pci virtio-net virtio-scsi virtio-blk virtio-balloon virtio-ring ## virtio 
            echo "schedutil" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

            ## ram tuning (16GB)
            echo 3 | sudo tee /proc/sys/vm/drop_caches
            echo 1 | sudo tee /proc/sys/vm/compact_memory
            echo 8192 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages

            echo "# Attach plugged usb device to running vm
ACTION==\"add\", SUBSYSTEM==\"usb\", ENV{DEVTYPE}==\"usb_device\", RUN+=\"$genxml %s{idVendor} %s{idProduct} $DOM\"" > /etc/udev/rules.d/00-vm.rules
            virsh attach-device $DOM "$kb" --live &>>$logs &!
            virsh attach-device $DOM "$mouse" --live &>>$logs &!
            ;;
        "release")
            rm /etc/udev/rules.d/00-vm.rules
            zsh ${vgatolinux} force &>>$logs
            sleep 5
            systemctl start nodm
            ;;
        *)
            ;;
    esac
    udevadm control --reload-rules
fi
