(setq dir-private "~/.emacs.d/private/")
(setq dir-config (concat dir-private "config/"))

(defun cfg(path &optional base)
  (unless base (setq base 0))
  (if (eq base 0)
      (setq base dir-config)
    (setq base dir-private)
    )
  (load (concat base path))
  )
(defun user-init()
  (if (not-emacs-for-apps)
      (cfg "pkgs/emacs-php-doc-block/php-doc-block.el" 1)
    (setq-default spacemacs-cache-directory "~/.emacs.d/.cache-apps/"))
  (cfg "basic.el")
  (cfg "langs/common.el" 1)
  ;; (load-file "~/.emacs.d/private/.spacemacs.fun")
  )
(defun user-config()
  (cfg "tmux/tmux-keys.el" 1)
  (require 'tmux-keys)
  (tmux-keys)
  (cfg "auth.el")
  (cfg "browse.el")
  (cfg "backups.el")
  (cfg "clipboard.el")
  (cfg "lsp.el")
  (cfg "term.el")
  (cfg "tramp.el")
)

(defun not-emacs-for-apps()
  (if (string= (getenv "EMACS_SERVER_NAME") "apps")
      nil
    t))

(defun is-emacs-for-apps()
  (if (string= (getenv "EMACS_SERVER_NAME") "apps")
      t
    nil))

(defun user-config-apps()
  (cfg "irc.el")
  (cfg "mails.el")
  )

(defun load-config()
  (if (not-emacs-for-apps)
      (user-config)
     (user-config-apps))
  (cfg "quirks.el")
  (cfg "keys.el")
  (cfg "theme.el")
  )

