-- we can read Lua syntax here!
return {
    ["auto_save_settings_interval_minutes"] = 15,
    ["bookmarks_items_per_page"] = 14,
    ["closed_rotation_mode"] = 0,
    ["color_rendering"] = true,
    ["coverbrowser_initial_default_setup_done"] = true,
    ["dev_no_c_blitter"] = false,
    ["device_id"] = "935453C9E0AC4A53ABA1728320D0F3DB",
    ["dicts_disabled"] = {},
    ["dicts_order"] = {},
    ["extra_plugin_paths"] = {
        [1] = "/home/fra/.config/koreader/plugins/",
    },
    ["filemanagermenu_tab_index"] = 4,
    ["folder_shortcuts"] = {},
    ["footer"] = {
        ["all_at_once"] = false,
        ["battery"] = true,
        ["book_chapter"] = false,
        ["book_chapter_max_width_pct"] = 30,
        ["book_time_to_read"] = true,
        ["book_title"] = false,
        ["book_title_max_width_pct"] = 30,
        ["bookmark_count"] = true,
        ["chapter_time_to_read"] = true,
        ["container_bottom_padding"] = 1,
        ["container_height"] = 14,
        ["disabled"] = false,
        ["frontlight"] = false,
        ["item_prefix"] = "icons",
        ["mem_usage"] = false,
        ["page_progress"] = true,
        ["pages_left"] = true,
        ["pages_left_book"] = false,
        ["percentage"] = true,
        ["progress_bar_min_width_pct"] = 20,
        ["progress_margin_width"] = 10,
        ["reclaim_height"] = false,
        ["skim_widget_on_hold"] = true,
        ["text_font_bold"] = false,
        ["text_font_size"] = 14,
        ["time"] = true,
        ["toc_markers"] = true,
        ["toc_markers_width"] = 2,
        ["wifi_status"] = false,
    },
    ["home_dir"] = "/home/fra/Documents/books",
    ["kosync"] = {
        ["auto_sync"] = true,
        ["pages_before_update"] = 1,
        ["userkey"] = "491387848f339af0148f2c1bc44f9412",
        ["username"] = "untoreh",
    },
    ["lastdir"] = "/home/fra/Documents/books/Jean-Philippe Aumasson/Serious Cryptography (158)",
    ["lastfile"] = "/home/fra/Documents/books/Jean-Philippe Aumasson/Serious Cryptography (158)/Serious Cryptography - Jean-Philippe Aumasson.epub",
    ["panel_zoom_enabled"] = {
        ["cbt"] = true,
        ["cbz"] = true,
    },
    ["panel_zoom_fallback_to_text_selection"] = {
        ["pdf"] = true,
    },
    ["quickstart_shown_version"] = 202103000000,
    ["reader_footer_mode"] = 8,
    ["screensaver_type"] = "disable",
    ["sdl_window"] = {
        ["left"] = 446,
        ["top"] = 88,
    },
    ["statistics"] = {
        ["convert_to_db"] = true,
        ["is_enabled"] = true,
    },
    ["style_tweaks"] = {
        ["footnote-inpage_epub_smaller"] = true,
        ["footnote-inpage_fb2"] = true,
    },
    ["text_lang_fallback"] = "en-US",
    ["toc_items_per_page"] = 14,
}
