tor
nss
base-devel
nc
ccache
lm_sensors
vulkan-icd-loader
aura-bin
emacs-gcc-wayland-devel-bin
neovim
mesa-d3d12
libgccjit
mpv
wget
unzip
imagemagick
inetutils
julia
net-tools
dos2unix
prettier

## pip3
mako PyYAML



