tor
nss
base-devel
nc
ccache
lm_sensors
android-tools
vulkan-icd-loader
aura-bin
emacs-gcc-wayland-devel-bin
neovim
mesa-d3d12
libgccjit
mpv
wget
gost
unzip
imagemagick
inetutils
gost
net-tools
dos2unix
btrfs-progs
prettier
gnome-keyring
dockerd
mu
#aur
emacs-native-comp-git-enhanced


# julia
julia
tree-sitter-julia-git # aur

## pip3 python
mako PyYAML supervisor grip cffi cython ansible black flake8 isort ptpython colorama decorator psutil pyte epc
# timeago


# theme
# sddm-theme-sweet
# color-scheme-sweet
# sweet-wallpapers
# plasma-theme-sweet
kvantum-theme-sweet-git
candy-icons-git
xcursor-sweet
sweet-folders-icons-git
sweet-theme-git
sweet-kde-git

# debugging
debuginfo-find
