tor
nss
base-devel
nc
ccache
lm_sensors
android-tools
vulkan-icd-loader
aura-bin
emacs-gcc-wayland-devel-bin
aspell
neovim
mesa-d3d12
libgccjit
mpv
wget
gost
unzip
imagemagick
inetutils
julia
net-tools
dos2unix
btrfs-progs
prettier

## pip3
python
mako PyYAML


# theme
# sddm-theme-sweet
# color-scheme-sweet
# sweet-wallpapers
# plasma-theme-sweet
kvantum-theme-sweet-git
candy-icons-git
xcursor-sweet
sweet-folders-icons-git
sweet-theme-git
sweet-kde-git
