tor
nss
base-devel
nc
ccache
lm_sensors
vulkan-icd-loader
aura-bin
emacs-gcc-wayland-devel-bin
neovim
mesa-d3d12
libgccjit
mpv
wget
gost
unzip
imagemagick
inetutils
julia
net-tools
dos2unix
btrfs-progs
prettier

## pip3
python
mako PyYAML



