#!/usr/bin/env bash

sleep_period=60s #seconds

mouse_x=0
mouse_y=0

movement_px=2
  mouse_x=$(xdotool getmouselocation 2>/dev/null |  sed -e 's/x://' -e 's/y//' -e 's/ screen:.*$//' -e 's/ //' | awk 'BEGIN {FS=":"} {print $1}')
  mouse_y=$(xdotool getmouselocation 2>/dev/null |  sed -e 's/x://' -e 's/y//' -e 's/ screen:.*$//' -e 's/ //' | awk 'BEGIN {FS=":"} {print $1}')

while true; do
    while [[ $(pidof xbmc.bin | wc -w) -gt 0 ]]; do
      xdotool mousemove $((mouse_x+${movement_px})) $((mouse_y+${movement_px}))
      xdotool mousemove $((mouse_x-${movement_px})) $((mouse_y-${movement_px}))
      sleep ${sleep_period}
    done
done
